spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            price-parsing-service:
            - uri: http://localhost:9090
            tg-bot-service:
            - uri: http://localhost:9091
