spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      client:
        simple:
          instances:
            price-parser-service:
             - uri: http://localhost:9090
            tg-bot-service:
             - uri: http://localhost:9091
            password-guard-service:
             - uri: http://localhost:9092
            temp-mail-service:
             - uri: http://localhost:9093
            environment-parser-service:
             - uri: http://localhost:9094
