spring:
  cloud:
    discovery:
      client:
        simple:
          order: 0
          instances:
            price-parsing-service: http://localhost:9090
            tg-bot-service: http://localhost:9091
