spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      client:
        simple:
          instances:
            price-parsing-service[0]:
             uri: http://localhost:9090
            tg-bot-service[0]:
             uri: http://localhost:9091
