spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fake_service_db
    username: postgres
    password: biba0218
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  sleuth:
    sampler:
      probability: 1.0

parsing:
  limit: 10
  durationInHour: 3h
